//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegratedFlghtDynamicSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpacecraftInfo
    {
        public SpacecraftInfo()
        {
            this.NUs = new HashSet<NU>();
        }
    
        public int Spacecraft_ID { get; set; }
        public int SpCrNumber { get; set; }
        public string SpCrName { get; set; }
        public string SpCrType { get; set; }
        public System.DateTime LaunchDateTime { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<NU> NUs { get; set; }
    }
}
