//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Поиск.
        /// </summary>
        internal static string NuApplyFilter {
            get {
                return ResourceManager.GetString("NuApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Delete All.
        /// </summary>
        internal static string NuDeleteAllCaption {
            get {
                return ResourceManager.GetString("NuDeleteAllCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Are you sure you want to delete all log histories for the current filter?.
        /// </summary>
        internal static string NuDeleteAllDataConfirmation {
            get {
                return ResourceManager.GetString("NuDeleteAllDataConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Actions.
        /// </summary>
        internal static string NuIndexActions {
            get {
                return ResourceManager.GetString("NuIndexActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Circle.
        /// </summary>
        internal static string NuIndexCircle {
            get {
                return ResourceManager.GetString("NuIndexCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Date time.
        /// </summary>
        internal static string NuIndexDateTime {
            get {
                return ResourceManager.GetString("NuIndexDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как От.
        /// </summary>
        internal static string NuIndexFrom {
            get {
                return ResourceManager.GetString("NuIndexFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Id.
        /// </summary>
        internal static string NuIndexID_NU {
            get {
                return ResourceManager.GetString("NuIndexID_NU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Modification.
        /// </summary>
        internal static string NuIndexModification {
            get {
                return ResourceManager.GetString("NuIndexModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Vector.
        /// </summary>
        internal static string NuIndexName {
            get {
                return ResourceManager.GetString("NuIndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как N_NU.
        /// </summary>
        internal static string NuIndexN_NU {
            get {
                return ResourceManager.GetString("NuIndexN_NU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Select.
        /// </summary>
        internal static string NuIndexSelect {
            get {
                return ResourceManager.GetString("NuIndexSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Vectors.
        /// </summary>
        internal static string NuIndexTitle {
            get {
                return ResourceManager.GetString("NuIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как до.
        /// </summary>
        internal static string NuIndexTo {
            get {
                return ResourceManager.GetString("NuIndexTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как X.
        /// </summary>
        internal static string NuIndexX {
            get {
                return ResourceManager.GetString("NuIndexX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Y.
        /// </summary>
        internal static string NuIndexY {
            get {
                return ResourceManager.GetString("NuIndexY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Z.
        /// </summary>
        internal static string NuIndexZ {
            get {
                return ResourceManager.GetString("NuIndexZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Идентификатор НУ.
        /// </summary>
        internal static string PredictTaskViewModel_IdNu_Name {
            get {
                return ResourceManager.GetString("PredictTaskViewModel_IdNu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Идентификатор должен быть задан!.
        /// </summary>
        internal static string PredictTaskViewModel_IdNu_RequiredMessage {
            get {
                return ResourceManager.GetString("PredictTaskViewModel_IdNu_RequiredMessage", resourceCulture);
            }
        }
    }
}
